### ISSUE TITLE
Document why bintray is better than packagecloud

### ISSUE THREAD

**Issue by josephholsten** [omniti-labs/ansible-dk#38]
I'm a huge fan of packagecloud, but we're currently using bintray. But looking at our use case, I can't justify us switching because:
- we want to host mac (& maybe someday windows) packages
- we want a landing page for installing, and bintray lets us point back to the project

Are there any other benefits to bintray over packagecloud or github releases?

**Comment by clintoncwolfe** [comment]
I really have no opinion.  Simply, I had heard of bintray, and had not heard of packagecloud - I've distributed a lot of stuff via source, but not via large binaries, so I just grabbed whatever seemed simplest.  It's probably not the best.
