### ISSUE TITLE
Add pip

### ISSUE THREAD

**Issue by clintoncwolfe** [omniti-labs/ansible-dk#5]
We now have a python 2.7 runtime, but we don't have pip or setuptools, which makes installing modules hard.  Make a software definition for it, and make sure that if you install a package, it goes to either /opt/ansible-dk, or ~/.ansible-dk/python  - NOT the system python.

**Comment by rpufky** [comment]
Commit 6315d3f should take care of this. Next step is to start bringing in more modules, but I'm going to do that work in another issue.
