### ISSUE TITLE
unable to install ansible-dk 

### ISSUE THREAD

**Issue by lmeyemezu** [omniti-labs/ansible-dk#68]
Hi, 
trying to install ansible-dk on ubuntu-16.04 vagrant vm.
I have the following error 
sudo apt-get install -y https://github.com/omniti-labs/ansible-dk.git
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package https://github.com/omniti-labs
E: Couldn't find any package by glob 'https://github.com/omniti-labs'
E: Couldn't find any package by regex 'https://github.com/omniti-labs'

Regards

**Comment by clintoncwolfe** [comment]
Hi lmeyemezu, 

  You cannot install the kit directly from the git repo. 

  To install ansible-dk, install the compiled OS packages, from https://github.com/omniti-labs/ansible-dk/releases .  For Ubuntu, the current release is https://github.com/omniti-labs/ansible-dk/releases/download/1.2.0/ansible-dk_1.2.0-1_amd64.deb .  

--CW
