### ISSUE TITLE
Ability to uninstall ansible-dk on OS X?

### ISSUE THREAD

**Issue by filler** [omniti-labs/ansible-dk#69]
Hello ansible-dk!

Sorry if this is obvious, but is there no way to uninstall ansible-dk?  I ran into this when trying to write a brew-cask formula for ansible-dk.

Let me know.  And thanks so much for all you do on this!  💖

**Comment by clintoncwolfe** [comment]
Here's a two-liner:

```
rm /usr/local/bin/ansible-dk
rm -rf /opt/ansible-dk
```

We don't drop files anywhere else, and the thing in /usr/local/bin is just a symlink, which we'd avoid if we could.

**Comment by filler** [comment]
Orly?  So theres nothing native to be done with `pkgutil` and related at the OS X level?

Efforts to date for getting `ansible-dk` into brew cask here: https://github.com/caskroom/homebrew-cask/pull/23983

**Comment by filler** [comment]
So now that `ansible-dk` is in `brew cask`, I can install and uninstall using standard means.  Im happy.  😄 

Closing this.
